### ISSUE TITLE
any plans to push this upstream

### ISSUE THREAD

**Issue by benswift** [Sardtok/pygments_processing#1]
Are there any plans to push this upstream? I've found them pretty receptive in the past.

**Comment by Sardtok** [comment]
Hi, Ben!
I hadn't really thought about it, I just hacked this together for my own use and figured that if anyone else needed to compile my org-mode files it should be available.
I'll create an issue in their Bitbucket, and see what they need to get this into the standard pygments package.

**Comment by benswift** [comment]
I've been using it for Processing code highlighting in LaTeX (via the
minted package). It's been great, thanks.

I've had a different lexer accepted for pygments in the past, I just
forked the bb repo[0] and sent a pull request, it was pretty
straightforward.

[0] https://bitbucket.org/birkenfeld/pygments-main
